task: detection

num_classes: 12
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/palyakere/Datasets/exdark/mount_data/exdark/images/
    ann_file: /home/palyakere/Datasets/exdark/annotations/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 32
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/palyakere/Datasets/exdark/mount_data/exdark/images/
    ann_file: /home/palyakere/Datasets/exdark/annotations/val.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False